
from options.cycle_gan_train_options import CycleGanTrainOptions
from options.cycle_mcd_train_options import CycleMcdTrainOptions
from options.mcd_train_options import McdTrainOptions
from options.test_options import TestOptions
assert CycleGanTrainOptions and CycleMcdTrainOptions and McdTrainOptions and TestOptions
